#import "modules/notes.typ": *
#import "@preview/finite:0.5.0": *
#show: thm-rules


#show: noteworthy.with(
  paper-size: "a4",
  language: "EN",
  title: "Topology",
  author: "Arjun Maneesh Agarwal",
  prof : "Upendra Kulkarni",
  course-desc: [
    - There will be homework which will be credited based on credible completion (not correctness)
    - There will be 2 tests/midsem and 1 endsem
    - There will be some quizzes

Moore Method: Prof. Moore used to hide all relevant textbooks and provide a list of definitions and results and call on kids. Prof. Kulkarni wants to use them for 1 lecture and tutorials (for some reason).
  ],
  contact-details: "thearjunagarwal.github.io",
  toc-title: "Table of Contents"
)
= Upendra Quotes
- "So how many times have you studied Topology? {3} Well, the first time was my fault. Well, this one is not mine."
- "I have learnt my lesson. I will try not to cause any heartburn anymore."
- "We will not need to write this unless dealing with some of the ... wrong headed examples. This book (Munkers) abhors in such examples."
- "In some way, I don't know why this course exists. Like they say controversial statements to increase TRP."
- "How many spaces do we care about which don't arise from metric spaces? Like there are some very important examples but do they warrant a whole course, I think not."
- "Go and read the definiton of box topology... and throw it in the dustbin"

= Lecture 1, 6 January 2026
== So what is Topology about?
Topology is not about open spaces, it is about continuous functions. Just like linear algebra is not about vectors and vector spaces but about linear transforms.

#definition(title: "Topology on a Set X")[
  Topology on a set $X$ is a subset of $P(X)$ closed under arbitrary unions and finite intersections.
]
#remark[
  Let ${S_alpha | alpha in J}$ be an indexed family of subsets of $X$. Then
  $
  union.big_(x in J) S_alpha = {x in X | exists alpha in J "s.t." x in S_alpha}\
  inter.big_(x in J) S_alpha = {x in X | forall alpha in J, x in S_alpha}
  $

  This implies every topology on $X$ contains $X$ and $emptyset$.
]
We normally denote a topological space as $(X, tau)$ but we ignore the $tau$ for most cases other than some counter-examples.#footnote["We will not need to write this unless dealing with some of the ... wrong headed examples. This book (Munkers) abhors in such examples."]

We will study more about geometric topology and glueing etc.
#example[
- For any $X$, discrete topology refers to $tau = P(X)$ while indiscrete topology refers to $tau = {emptyset, P(X)}$.
- Finite Complement Topology#footnote[Will come in as the Zariski Topology for the affine line, words I don't know the meaning of]
- Countable Complement Topology
- The usual topologies of $RR, RR^n$, any metric spaces.
]
#definition(title: "Basis for a Topology")[
  The basis for a topology on $X$ is a subset $cal(B)$ of $P(X)$ such that
  $
  union.big_(v in cal(B)) v = X
  $
  Also, given $x in B_1 inter B_2, B_i in cal(B)$:
  $
  exists B_3 in cal(B) "s.t." x in B_3 subset B_1 inter B_2
  $
  Given an abstract basis $B$ in $P(X)$, the topology generated by $B$ consists of those sets $U$ such that $forall x in U, exists B in cal(B) "s.t." x in B subset.eq U$.
]
#rmk[
  This gives a topology. Also, note: each basis element is open.
]
#thm[
  $U$ is open in this topology $<==>$ $U$ is union of basis elements
]
#proof[
  #todo[?]
]
#definition(title : "Subbasis")[
  An abstract subbasis is any subset $cal(S)$ of $P(X)$ such that
  $
  union.big_(v in cal(S)) v = X
  $
  then the associated basis is set of all finite intersections of elements of $cal(S)$.
]

Suppose I am separately given $tau$, a topology on $X$ and $cal(B)$ is an abstract basis in $P(X)$. We say $cal(B)$ generates $tau$ $<==>$ if each $B in cal(B)$ is in $Tau$ and for any $U in Tau$ is union of elements in $B$.
#definition[
If $tau_1, tau_2$ are two topologies on $X$, we say $tau_2$ is finer than $tau_1$ and $tau_1$ is corser than $tau_2$ if $tau_1 subset.eq tau_2$.
]

== $(X, d)$ metric space
Take $cal(B) = "open balls", B_epsilon(a) = {x in X | d(x,a) < epsilon}$. This is a basis by triangle inequality. 
#example[
  - $RR$ has basis $(a,b)$
  - $RR^2$ has basis balls ($l_2$) as well as diamonds ($l_1$) (we have already seen that all norms are equivalent on finite dimensional $RR^n$) 
]

= Lecture 2, January 7 2026
#todo[]
= Lecture 3, January 8 2026
== Continuity
#defn[
  $X -->^f Y$ is continuous\
  $<==>$ $f^(-1)("open in" Y)$ is open in $X$\
  $<==>$ $f^(-1)("closed in" Y)$ is closed in $X$\
  $<==>$ $f(overline(A)) subset overline(f(A))$\
  $<==>$ $f$ is continuous at each $x in X$
]
#rmk[
  To determine if $f$ is cont, it is enough to check $f^(-1)("basis elements")$ is open.
]
#cor[
  $X -->^f Y "is continuous" ==> X_"finer" -->^f Y "is continuous"$
]
#example[
  Following are continuous:
  - Any $X$, $X -->^id X$
  - $X -->^f Y -->^g Z$ where $f, g$ is continuous then $g compose f$ is continuous.
  - any $X -->^"constant" "any" Y$
  - Inclusion of any subspace
  - restriction of domain
  - extend codomain or restrict codomain if possible
  - local formulation of continuity. If ${V_alpha}_(alpha in I)$ is an open cover of $X$ then $X -->^f Y$ is continuous $<==>$ $f|_(V_alpha) : V_alpha --> Y$ is continuous $forall alpha$
  - Pasting Lemma for finitely many closed sets
]
== Product Topology
Let's say we somehow have
$
RR times RR -->^(+, dot) RR\ 
RR -->^(-) RR\ 
RR backslash {0} -->^(1/x) RR\ 
$
are continuous. This gives as many more. Say we want to show $x^2$ is continuous
$
&RR -->^Delta &RR times RR --> RR\
&x |-> &(x,x)\
& &(x,y) |-> &x y
$

Basically, we want that if $f, g: RR --> RR$ are continuous then $f + g : RR --> RR$ is continuous. We can do that via the continuity of $f times g : RR --> RR times RR$.

Thus us what we want our product topology to achieve.
#claim[
  If $X -->^(f_i) Y_i $ is continuous then $X -->^(f_1 times f_2) Y_1 times Y_2$ is continuous.
]

Let's try using $V_1 times V_2$ where $V_i$ is open in $Y_i$ should be open in $Y_1 times Y_2$.
$
(V_1 times V_2) inter (W_1 times W_2) = (V_1 inter W_1) times (V_2 inter W_2)
$
but
$
(V_1 times V_2) union (W_1 times W_2) != (V_1 union W_1) times (V_2 union W_2)
$
To get the latter to be true, we define it as
#definition[
  $Y_1 times Y_2$ becomes a topological space by treating open $times$ open is a basis.
]

Furthermore, observe that $Y_1 times Y_2 -->^p_i Y_i $ being the projection maps are continuous as:
$
p_1^(-1)(V_1) = V_1 times Y_2\
p_2^(-1)(V_2) = Y_1 times V_2\
p_1^(-1)(V_1) inter p_2^(-1)(V_2) = V_1 times V_2
$

This implies that the product topology is the coarsest topology on $Y_1 times Y_2$ that makes projections continuous.

#claim[
  $(Y_1 times Y_2, p_1, p_2)$ is the universal topological space with continuous maps to $Y_1$ and $Y_2$.
]
This means, given continuous $Z ->^(f_i) Y_i$ then $exists ! f : Z -> Y_1 times Y_2$ such that
$
f_i = p_i compose f
$
#proof[
  #todo[]
]
#rmk[
  This leads to the category of topological spaces and continuous map.
]
== Isomorphism of Topological Spaces
Notice, Isomorphism is just renaming while preserving structure.

#defn(title:"Bad Hopeful Definition")[
  A bijective continuous map
]
Why is this bad? Consider $(X, tau)$ then
$
(X, tau) -->^id (X, tau')  
$
is continuous and bijective if $tau$ is finer. This has by no means preserved structure!

#definition(title:"Isomorphism")[
  An isomorphism is a map
  $
  X -->^f Y "s.t."\
  exists X <--^g Y "with"\
  f g = id_Y, g f = id_X\
  $
  (Such $g_1$ if it exists is unique: $g_2 = (g_1 f) g_2 = g_1$)
]
#defn[
  A continuous map $f : X --> Y$ is called a homeomorphism if exists a continuous map $g : Y --> X$ such that $f g = id_Y, g f = id_X$
]